### PR TITLE
Show Mouse Feature To Veil 

### PR DESCRIPTION
**Pull request by IDoTheHax**
Allows for a user to show their mouse without having to pause the game,
open the chat or press esc

Handy feature ig?

### CODE REVIEW

**Comment by Xyndra** [comment]
Ever tried F3+Esc?

**Comment by IDoTheHax** [comment]
F3 Esc is what it's based on but that pauses the game and doesn't work on multiplayer

**Comment by IDoTheHax** [comment]
While f7 allows you to control Minecraft while still having a mouse

**Comment by Ocelot5836** [comment]
This is out of scope for Veil. F3+Esc and chat are more than good enough to free the mouse.

**Pull request closed without merging**
